spring:
  application:
    name: sharding-base-on-time
  redis:
    host: redis.dev.runan.life
    port: 6379
    lettuce:
      pool:
        max-wait: 10000ms
        max-active: 8
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: -1

  datasource:
    actualDataNodes: shard_01.order_info_$->{2207..2212}
    sqlShow: true
    druid:
      max-active: 10
  shard:
    data-sources:
      # 因为该库为分表的库，所以此处名字不用和上面真实节点库名规则一样
      shard_01:
        username: root
        password: mysqlroot
        url: jdbc:mysql://mysql.dev.runan.life:3306/shard_01?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      default:
        username: root
        password: mysqlroot
        url: jdbc:mysql://mysql.dev.runan.life:3306/shard_default?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        initial-size: 2
        max-active: 10
    tables:
      user_info:
        logic-table: user_info
        actual-data-nodes: shard_01.user_info_$->{1..2}
        sharding-columns: id
mybatis:
  mapper-locations: mapper/**/*.xml